---
- name: install ircd-irc2
  apt: pkg=ircd-irc2 state=installed

- name: Copy across IRCD configuration
  template: 
    src=ircd.conf.j2 
    dest=/etc/ircd/ircd.conf
  notify:
  - restart ircd

- name: Copy across IRCD MOTD
  template: 
    src=ircd.motd.j2 
    dest=/etc/ircd/ircd.motd
  notify:
  - restart ircd
